apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
    name: cos-nvidia-installer
    namespace: kube-system
spec:
  template:
    metadata:
      labels:
        name: cos-nvidia-installer
    spec:
      hostNetwork: true
      hostPID: true
      volumes:
      - name: dev
        hostPath:
          path: /dev
      - name: nvidia-overlay
        hostPath:
          path: /home/kubernetes/bin/nvidia
      - name: os-release
        hostPath:
          path: /etc/os-release
      - name: sysrq
        hostPath:
          path: /proc/sysrq-trigger
      containers:
      - image: gcr.io/vishnuk-cloud/cos-nvidia-driver-install@sha256:4af21c51d74e3cf1977b3909e2a194ebe7b03d63218a4b8a628033ad7767e121
        command: ["/bin/sh", "-c"]
        args: ["usr/bin/nvidia-installer.sh && sleep infinity"]
        name: nvidia-driver-installer
        resources:
          requests:
            cpu: 0.15
        securityContext:
          privileged: true
        env:
          - name: BASE_DIR
            value: "/rootfs/nvidia"
        volumeMounts:
        - name: nvidia-overlay
          mountPath: /rootfs/nvidia
        - name: dev
          mountPath: /dev
        - name: os-release
          mountPath: /rootfs/etc/os-release
        - name: sysrq
          mountPath: /sysrq
